// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeF2TrxmRaUb3dXhiy84lStd6r9l8WT2E',
    appId: '1:15077516471:android:a343a04768a52dacfc1932',
    messagingSenderId: '15077516471',
    projectId: 'learnfirebase-24a2b',
    storageBucket: 'learnfirebase-24a2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPlVbIkaPjICv8P-z_PrkpvvTMRUKDtKw',
    appId: '1:15077516471:ios:f20c78ba17dd5ed2fc1932',
    messagingSenderId: '15077516471',
    projectId: 'learnfirebase-24a2b',
    storageBucket: 'learnfirebase-24a2b.appspot.com',
    androidClientId: '15077516471-q7pj9mje2pamvaitms4dikba9v3rp33c.apps.googleusercontent.com',
    iosClientId: '15077516471-efbgvln92gepv5clmhdkresenhnn369k.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFirebaseCrud',
  );
}
